name: Auto Commit Bot

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # ensures proper auth
        ref: main  # force correct branch

    - name: Set Git config
      run: |
        git config --global user.name 'AutoCommit Bot'
        git config --global user.email 'autocommit@users.noreply.github.com'

    - name: Make changes
      run: |
        echo "Last updated: $(date -u)" > last_updated.txt

    - name: Commit & Push changes
      run: |
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
        else
          git commit -m "Auto update: $(date -u)"
          git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
